name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore
    - name: Install dotnet tools 
      run: dotnet tool install --global dotnet-sonarscanner
    - name: Start sonar scaner
      env:
        SONAR_SECRET: ${{ secrets.SONAR_TOKEN }}
      run: dotnet sonarscanner begin /d:sonar.host.projectKey="thinhnotes_PluralsightDownload" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.organization="$SONAR_SECRET" /d:sonar.login="$SONAR_SECRET" /d:sonar.branch.name="${GITHUB_REF#refs/heads/}"
    - name: Build
      run: dotnet build --configuration Release --no-restore -o release
    - name: Build
      run: dotnet sonarscanner end /d:sonar.login="${{ secrets.AWS_ACCESS_KEY_ID }}"      
    - name: Zip Folder
      run: zip -r release.zip release
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v1-release
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: release.zip
        asset_name: release.zip
        tag: PluralsightDownload-1.0.0
        overwrite: true

